config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphql/explorer", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  get "/health", to: proc { [200, {}, ["ok"]] }

  devise_for :users, path: "account", controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords"
  }
  get "/account/sign_in/ldap" => "users/ldaps#new", :as => :new_ldap_user_session

  # /admin
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web, at: "/admin/sidekiq"
    mount ExceptionTrack::Engine, at: "/admin/exception-track"
    mount PgHero::Engine, at: "/admin/pghero"
  end

  namespace :admin do
    root to: "dashboards#show"
    resource :dashboard do
      collection do
        post :reindex
      end
    end
    resource :settings do
      collection do
        post :test_mail
      end
    end
    resources :integrations
    resources :groups do
      member do
        post :restore
      end
    end
    resources :users do
      member do
        post :restore
      end
    end
    resources :repositories do
      member do
        post :restore
      end
    end
    resources :docs do
      member do
        post :restore
      end
    end
    resources :comments
    resources :shares
    resources :issues
    resources :notes do
      member do
        post :restore
      end
    end
  end

  # short attachment url
  get "/uploads/:id" => "blobs#show", :as => :upload

  resources :notifications do
    collection do
      get :all
      post :read
      delete :clean
    end
  end

  resource :account_settings, as: :account_settings, path: "account/settings" do
    collection do
      get :account
    end
  end

  root to: "dashboards#index"
  resource :dashboard do
    member do
      get :activities
      get :docs
      get :repositories
      get :groups
      get :stars
      get :explore
    end
  end
  # GET /new
  get "new", to: "repositories#new", as: :new_repository
  # GET /new/import
  get "new/import", to: "repositories#import", as: :import_repository
  resource :autocomplete do
    collection do
      get :users
    end
  end

  # GET /groups/new, POST /groups
  resources :groups, only: %i[new create] do
    member do
      get :search
    end
    resources :group_members, as: :members, path: :members
    resource :group_settings, as: :settings, path: :settings
  end
  # GET /notes/new, POST /notes
  resources :notes, only: %i[new create]
  resources :versions
  resource :search do
    collection do
      get :docs
      get :repositories
      get :groups
      get :users
      get :notes
      get :issues
    end
  end
  resources :comments do
    member do
      get :reply
      get :in_reply
    end
    collection do
      post :watch
      delete :watch
    end
  end
  resources :shares

  # NOTE! Keep :profile routes bottom of routes.rb
  resources :repositories, only: %i[index create]
  resources :users, id: /[#{BlueDoc::Slug::FORMAT}]*/o, path: "", as: "users" do
    member do
      post :follow
      delete :unfollow
    end
    resources :notes, only: %i[index create edit show update destroy] do
      member do
        get :raw
        get :versions
        patch :revert
        post :action
        delete :action
        # PRO-begin
        get :readers
        # PRO-end
        post :pdf
      end
    end
    resources :repositories, path: "", as: "repositories", only: %i[show update destroy] do
      resource :services do
        collection do
          get :jira_issues
        end
      end
      member do
        get :docs, path: "docs/list"
        get :search, path: "docs/search"
        post :action
        delete :action
      end
      resource :repository_settings, path: "settings", as: :settings do
        collection do
          get :show, path: "profile"
          put :update, path: "profile"
          patch :update, path: "profile"
          delete :destroy, path: "profile"
          get :advanced
          patch :transfer
          get :docs
          post :docs
          post :export
          get :export
          get :collaborators
          post :collaborators
          post :collaborator
          delete :collaborator
          post :retry_import
          get :integrations
          post :jira
        end
      end
      resources :docs, only: %i[new create]
      resources :labels, path: "issues/labels"
      resources :issues do
        collection do
          get :closed
        end
        member do
          post :assignees
          post :labels
        end
      end
      resources :docs, path: "", only: %i[show edit update destroy] do
        member do
          get :raw
          post :pdf
          get :lock
          post :lock
          post :action
          delete :action
          get :versions
          patch :revert
          patch :abort_draft
          post :share
          # PRO-begin
          get :readers
          # PRO-end
        end
      end
    end
  end
end

app/models/activities/note.rb
# frozen_string_literal: true

module Activities
  class Note < Base
    attr_accessor :note

    def initialize(note)
      @note = note
      super()
    end

    def star
      return if note.private?

      # actor followers
      user_ids = actor.follower_ids

      Activity.track_activity(:star_note, note, user_id: user_ids, actor_id: actor_id)
    end
  end
end

app/models/note.rb
# frozen_string_literal: true

class Note < ApplicationRecord
  include Slugable
  include Activityable
  include Smlable
  include Reactionable
  include Exportable

  second_level_cache expires_in: 1.week

  validates :title, presence: true, length: {maximum: 255}
  validates :slug, length: {maximum: 200}, uniqueness: {scope: :user_id, case_sensitive: false}
  validates :description, length: {maximum: 200}

  scope :recent, -> { order("id desc") }

  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy

  depends_on :privacy, :soft_delete, :publish, :body_touch, :versions, :search, :watches, :auto_correct

  def to_path(suffix = nil)
    "#{user.to_path}/notes/#{slug}#{suffix}"
  end

  # return next and prev of notes in same user
  # { next: Note, prev: Note }
  def prev_and_next_of_notes(with_user: nil)
    result = {next: nil, prev: nil}
    recent_docs = user.notes.recent
    if with_user&.id != user_id
      recent_docs = recent_docs.publics
    end
    idx = recent_docs.find_index { |note| note.id == id }
    return result if idx.nil?
    if idx < recent_docs.length
      result[:next] = recent_docs[idx + 1]
    end
    if idx > 0
      result[:prev] = recent_docs[idx - 1]
    end
    result
  end

  class << self
    def create_new(user_id, slug: nil, title: nil)
      note = Note.new
      note.format = "sml"
      note.user_id = user_id
      note.title = title || "New Note"
      note.slug = slug.blank? ? BlueDoc::Slug.random(seed: 999999) : slug
      note.save!
      note
    rescue ActiveRecord::RecordNotUnique
      slug = nil
      retry
    end
  end
end

app/models/note/auto_correct_dependency.rb
# frozen_string_literal: true

class Note
  before_validation :auto_correct_attributes

  private

  def auto_correct_attributes
    self.title = AutoCorrect.format(title) if title_changed?
    self.description = AutoCorrect.format(description) if description_changed?
  end
end

app/models/note/body_touch_dependency.rb
# frozen_string_literal: true

class Note
  before_save :touch_body_updated_at_on_publish

  def body_updated_at
    self[:body_updated_at] || updated_at
  end

  def body_touch?
    publishing? || body.changed? || body_sml.changed?
  end

  private

  def touch_body_updated_at_on_publish
    if body_touch?
      self.body_updated_at = Time.now
    end
  end
end

app/models/note/privacy_dependency.rb
# frozen_string_literal: true

class Note
  enum privacy: %i[private public], _prefix: :is
  scope :publics, -> { where(privacy: :public) }

  before_update :check_on_make_private

  def private?
    is_private?
  end

  def public?
    is_public?
  end

  private

  def check_on_make_private
    if privacy_changed? && private?
      destroy_depend_activities

      # FIXME: Remove depends actions
    end
  end
end

app/models/note/publish_dependency.rb
# frozen_string_literal: true

class Note
  attr_accessor :_publishing

  def publishing!
    self._publishing = true
  end

  def publishing?
    _publishing == true
  end
end

app/models/note/search_dependency.rb
# frozen_string_literal: true

class Note
  include Searchable

  def as_indexed_json(_options = {})
    {
      slug: slug,
      title: title,
      body: body_plain,
      search_body: _search_body,
      user_id: user_id,
      public: public?,
      deleted: deleted?
    }
  end

  def indexed_changed?
    saved_change_to_deleted_at? ||
      saved_change_to_title? ||
      saved_change_to_privacy? ||
      saved_change_to_user_id? ||
      body.changed?
  end

  def _search_body
    [user&.fullname, to_path, body_plain].join("\n\n")
  end
end

app/models/note/soft_delete_dependency.rb
# frozen_string_literal: true

class Note
  include SoftDelete

  # PRO-begin
  set_callback :restore, :before do
    restore_dependents(:comments)
  end
  # PRO-end
end

app/models/note/versions_dependency.rb
# frozen_string_literal: true

class Note
  after_create :track_note_version_on_create
  after_update :track_note_version_on_update

  has_many :versions, -> { order("id desc") }, class_name: "NoteVersion", as: :subject

  # Revert to a version, this still create a new version
  def revert(version_id, user_id: nil)
    version = versions.find_by_id(version_id)
    if version.blank?
      errors.add(:base, "Revert version is invalid")
      return false
    end

    update(body: version.body_plain, body_sml: version.body_sml, format: version.format)
  end

  private

  def track_note_version_on_create
    _track_note_version
  end

  def track_note_version_on_update
    if body_touch?
      _track_note_version
    end
  end

  def _track_note_version
    versions.create!(user_id: user_id, body: body, body_sml: body_sml, format: self.format)
  end
end

app/models/note/watches_dependency.rb
# frozen_string_literal: true

class Note
  after_create :triger_watch_on_create

  def watch_comment_status_by_user_id(user_id)
    action = watch_comment_by_user_actions.where("user_type = 'User' and user_id = ?", user_id).take
    return action.action_option == "ignore" ? "ignore" : "watch" if action

    "unwatch"
  end

  private

  def triger_watch_on_create
    User.create_action(:watch_comment, target: self, user_type: "User", user_id: user_id)
  end
end

app/controllers/admin/notes_controller.rb
# frozen_string_literal: true

class Admin::NotesController < Admin::ApplicationController
  before_action :set_note, only: %i[destroy restore]

  def index
    @notes = Note.unscoped.where(privacy: "public").includes(:user).order("id desc")
    if params[:user_id]
      @notes = @notes.where(user_id: params[:user_id])
    end
    if params[:q]
      q = "%#{params[:q]}%"
      @notes = @notes.where("title ilike ? or slug ilike ? or description ilike ?", q, q, q)
    end
    @notes = @notes.page(params[:page])
  end

  def destroy
    @note.destroy
    redirect_to admin_notes_path(user_id: @note.user_id, q: @note.slug), notice: t(".Note was successfully deleted")
  end

  def restore
    @note.restore
    redirect_to admin_notes_path(user_id: @note.user_id, q: @note.slug), notice: t(".Note was successfully restored")
  end

  private

  def set_note
    @note = Note.unscoped.find(params[:id])
  end

  def note_params
    params.require(:note).permit!
  end
end

app/controllers/notes_controller.rb
# frozen_string_literal: true

class NotesController < Users::ApplicationController
  # PRO-start
  depends_on :readers, :exports
  # PRO-end

  before_action :authenticate_anonymous!

  before_action :set_user, except: %i[new create]
  before_action :set_note, only: %i[show edit update destroy versions revert raw action]
  before_action :authenticate_user!, except: %i[index show readers raw]

  def index
    @notes = @user.notes.recent
    if @user != current_user
      @notes = @notes.publics
    end
    @notes = @notes.page(params[:page])
  end

  def new
    @user = current_user
    @note = Note.new(slug: params[:slug])
  end

  def create
    @user = current_user
    @note = @user.notes.new(note_params)
    if @note.save
      redirect_to @note.to_path("/edit")
    else
      render "new"
    end
  end

  def show
    authorize! :read, @note

    @between_notes = @note.prev_and_next_of_notes(with_user: current_user)
    @readers = @note.read_by_user_actions.order("updated_at desc").limit(5)

    current_user&.read_note(@note)

    render :show, layout: "reader"
  end

  def edit
    authorize! :update, @note

    render :edit, layout: "editor"
  end

  def update
    authorize! :update, @note

    if note_params[:body_sml].blank?
      note_params[:format] = @note.format
    end

    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note.to_path, notice: t(".Note was successfully updated") }
        format.json { render json: {ok: true, note: {slug: @note.slug}} }
      else
        format.html { render :edit, layout: "editor" }
        format.json { render json: {ok: false, messages: @note.errors.full_messages} }
      end
    end
  end

  def destroy
    authorize! :destroy, @note

    @note.destroy
    redirect_to @user.to_path("/notes"), notice: t(".Note was successfully deleted")
  end

  # GET /:user/notes/:slug/raw
  def raw
    authorize! :read, @note

    respond_to do |format|
      format.html { render :raw, layout: "editor" }
      format.text { render plain: @note.body_plain }
    end
  end

  # GET /:user/:repo/:slug/versions
  def versions
    authorize! :update, @note

    @current_version = @note.versions.includes(:user).first
    @previous_version = @note.versions.second
    @versions = @note.versions.where("id <> ?", @current_version.id).includes(:user).page(params[:page]).per(7)
    render "versions", layout: "reader"
  end

  # POST /:user/:repo/:slug/revert
  def revert
    authorize! :update, @note

    version_id = params.permit(:version_id)[:version_id]
    if @note.revert(version_id, user_id: current_user.id)
      redirect_to @note.to_path, notice: t(".Note was successfully reverted")
    else
      redirect_to @note.to_path("/versions"), alert: t(".Revert failed, please check a exists version")
    end
  end

  # POST /:user/notes/:slug/action
  # DELETE /:user/notes/:slug/action
  def action
    authorize! :read, @note

    if request.post?
      User.create_action(params[:action_type], target: @note, user: current_user)

      if params[:action_type] == "star"
        Activities::Note.new(@note).star
      end
    else
      User.destroy_action(params[:action_type], target: @note, user: current_user)
    end
    @note.reload
  end

  private

  def set_note
    @note = @user.notes.find_by_slug(params[:id])
    raise ActiveRecord::RecordNotFound if @note.blank?
  end

  def note_params
    params.require(:note).permit(:title, :body, :body_sml, :slug, :format, :privacy, :description)
  end
end

app/helpers/notes_helper.rb
# frozen_string_literal: true

module NotesHelper
  def note_title_tag(note)
    return "" if note.blank?
    return "" if note.user.blank?

    link_to truncate(note.title, length: 100), note.to_path, class: "note-link", title: note.title
  end
end

app/views/notes/_card.html.erb
<% if note %>
  <div class="doc-card">
    <div class="mb-1 text-main">
      <%= note_title_tag(note) %>
    </div>
    <div class="path">
      <%= user_name_tag(note.user, with_icon: true) %> /
      <%= link_to t(".Notes"), user_notes_path(note.user, with_icon: true) %>
    </div>
  </div>
<% end %>

app/views/notes/_readers.html.erb
<div class="note-readers text-gray">
<a href="<%= note.to_path("/readers") %>" class="readers-link" data-remote="true">
  <span class="avatars">
    <% readers.take(5).map do |action| %>
      <%= user_avatar_tag(action.user, style: :tiny, link: false)%>
    <% end %>
  </span>
  <% if note.reads_count > 5 %>
  ... <%= note.reads_count %> <%= t(".people") %>
  <% end %>
  <%= t(".has read") %>
</a>

<% if action_name == "readers" %>
<details class="details-reset details-overlay details-overlay-dark" open>
  <summary></summary>
  <details-dialog class="box d-flex flex-column anim-fade-in fast">
    <div class="box-header">
      <button data-close-dialog class="box-btn-octicon btn-octicon float-right"><i class="fas fa-times"></i></button>
      <h3 class="box-title"><%= t(".Reader list") %></h3>
    </div>
    <div class="box-body user-list">
      <% readers.each do |action| %>
        <div class="user-item">
          <%= user_avatar_tag(action.user, style: :tiny) %>
          <%= user_name_tag(action.user) %>
          <span class="time-box">
            <%= timeago action.updated_at.to_date %>
          </span>
        </div>
      <% end %>
    </div>
  </details-dialog>
</details>
<% end %>
</div>

app/views/notes/_versions.html.erb
<%= render partial: "versions/version", collection: @versions, as: :version %>
<%= paginate @versions, remote: true %>

app/views/notes/action.js.erb
if ($(".data-action-button-reload").length > 0) {
  Turbolinks.visit(window.location);
} else {
  var btnAction = $(".note-<%= @note.id %>-<%= params[:action_type ] %>-button");
  var btn = $("a", btnAction);
  <% if request.post? %>
    btn.attr("data-method", "delete");
    $("span", btnAction).text(btn.attr("data-undo-label"));
  <% else %>
    btn.attr("data-method", "post");
    $("span", btnAction).text(btn.attr("data-label"));
  <% end %>
}

app/views/notes/edit.html.erb
<%= form_with(model: [@user, @note],
  url: user_note_path(@user),
  local: true,
  remote: true,
  id: "note-form") do |form| %>
  <% if @note.errors.any? %>
    <details class="note-validation-error details-reset details-overlay" open>
      <summary></summary>
      <details-dialog class="box box--overlay d-flex flex-column anim-fade-in fast">
        <div class="box-body overflow-auto">
          <button class="btn-cancel" type="button" aria-label="Close dialog" data-close-dialog>
            <%= icon_tag "cancel" %>
          </button>
          <div class="mx-5 my-2">
            <div class="mb-4 text-center text-red">
              <p style="font-size: 32px"><%= icon_tag("error") %></p>
              <div class="mb-1 text-red">
                <strong><%= t(".Note publish failed, because there has count issues", count: @note.errors.count) %></strong>
              </div>
            </div>
            <ul class="ml-3">
              <% @note.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </details-dialog>
    </details>
  <% end %>
  <div id="editor-form">
    <div class="editor-navbar">
      <div class="navbar-title">
        <%= logo_tag href: @user.to_path do %><span class="blue">Blue</span>Doc<% end %>
        <span class= "divider">/</span>
        <%= user_name_tag @user %>
        <span class= "divider">/</span>
        <a href="<%= @note.to_path %>" class="note-link"><%= @note.title || t(".New Note") %></a>
        <% if @note.private? %>
          <span class="label label-private icon-middle-wrap ml-2"><%= icon_tag("lock") %><%= t(".Private") %></span>
        <% end %>
        <span class="editor-message"></span>
      </div>
      <div class="navbar-buttons">
        <button type="submit" class="btn btn-primary"><%= t(".Publish") %></button>
        <%= react_component "notes/EditorSetting", {
          slug: @note.slug,
          description: @note.description,
          privacy: @note.privacy,
          prefix: user_notes_path(@user),
          saveURL: user_note_path(@user),
        } %>
      </div>
    </div>
  </div>
  <div class="editor-container">
    <%= react_component "Editor", {
      format: @note.format,
      title: @note.title,
      body: @note.body_plain,
      body_sml: @note.body_sml_plain,
      name: "note[body_sml]",
      markdownName: "note[body]",
      formatName: "note[format]",
      titleName: "note[title]",
      plantumlServiceHost: Setting.plantuml_service_host,
      mathJaxServiceHost: Setting.mathjax_service_host
    } %>
  </div>
<% end %>

app/views/notes/index.html.erb
<% title_tag "#{@user.name} - #{t(".Notes")}" %>

<div class="flex-wrap">
  <div class="aside-wrap">
    <%= render "/users/sidebar" %>
  </div>
  <div class="main-wrap">
    <div class="main-content">
      <div class="user-notes">
        <h2 class="sub-title">
          <span class="title"><%= t(".Notes") %></span>
          <%= link_to t(".New Note"), new_note_path, class: "btn btn-primary btn-sm float-right" %>
        </h2>
        <% if @notes.blank? %>
        <div class="blankslate no-data no-note">
          <p><%= t(".No notes") %></p>
        </div>
        <% else %>
        <ul class="cards-container recent-notes">
          <% @notes.each do |note| %>
            <li class="card recent-note-item mb-2">
              <div class="title">
                <%= note_title_tag(note) %>
                <% if note.private? %>
                  <span class="label label-private icon-middle-wrap ml-2"><%= icon_tag("lock") %><%= t(".Private") %></span>
                <% end %>
              </div>
              <% if note.description.present? %>
              <div class="description">
                <%= note.description %>
              </div>
              <% end %>
              <div class="info">
                <%= timeago note.body_updated_at %>
              </div>
              <div class="action action-icon">
                <% if can? :update, note %>
                  <%= link_to icon_tag("edit"), note.to_path("/edit"), class: "btn-edit" %>
                <% end %>
                <% if can? :delete, note %>
                  <%= link_to icon_tag("trash"), note.to_path, class: "btn-delete", data: { method: :delete, confirm: t(".Are you sure delete?") }  %>
                <% end %>
              </div>
            </li>
          <% end %>
        </ul>
        <% end %>
      </div>
      <%= paginate @notes %>
    </div>
  </div>
</div>

app/views/notes/new.html.erb
<% title_tag t(".New Note") %>

 <div class="container">
  <%= react_component "notes/NewNote", {
    note: @note.as_rc_json(only: %i[id slug title description privacy]),
    user: current_user.as_json(only: %i[id slug name], methods: :to_url),
    action: user_notes_path(current_user),
  } %>
</div>

app/views/notes/raw.html.erb
<div class="markdown-body markdown-raw">
  <%= react_component "MarkdownRaw", { value: @note.body_plain } %>
</div>

app/views/notes/readers.js.erb
document.querySelector(".note-readers").outerHTML = '<%= j(render("readers", note: @note, readers: @readers, state: "open")) %>';

app/views/notes/show.html.erb
<% title_tag @note ? @note.title : t(".Not found") %>

<% content_for :subnav do %>
<div class="navbar-wide-mode" style="display: none">
  <a href="#" class="btn btn-wide-mode-exit"><%= t(".Exit Fullscreen") %></a>
</div>
<% end %>

<div class="doc-page note-page d-flex flex-wrap flex-lg-nowrap">
  <div class="doc-center flex-auto">
    <div class="doc-main">

      <div class="navbar-title">
        <span class="hide-sm">
          <%= user_name_tag @user %>
          <span class="divider">/</span>
        </span>
        <%= link_to t(".Notes"), user_notes_path(@user) %>
      </div>
      <h1 class="doc-title">
        <%= @note.title %>
        <% if @note&.private? %>
          <span class="label label-private icon-middle-wrap ml-2"><%= icon_tag("lock") %><%= t(".Private") %></span>
        <% end %>
      </h1>

      <div class="reader-navbar text-main float-right">
        <% if @note %>
        <div class="navbar-buttons">
          <% if can? :read, @note %>
            <%= action_button_tag(@note, :star, icon: "star", class: "btn btn-sm btn-link btn-star-doc") %>
          <% end %>

          <% if can? :update, @note %>
          <%= link_to icon_tag("edit", label: t(".Edit")), edit_user_note_path(@user, @note), class: "btn btn-sm btn-link btn-edit-doc hide-sm ml-1" %>
          <% end %>

          <details class="dropdown details-overlay details-reset d-inline-block ml-2">
            <summary class="link-gray-dark"><%= icon_tag("more") %></summary>
            <ul class="dropdown-menu dropdown-menu-sw">
              <li><a class="dropdown-item" data-close-dialog target="_blank" href="<%= raw_user_note_path(@user, @note) %>"><%= t(".Markdown") %></a></li>
              <% if can? :update, @note %>
                <li><%= render "/docs/export_pdf", doc: @note %></li>
              <% end %>
              <li><a class="dropdown-item btn-print-doc" data-close-dialog href="#"><%= t(".Print document") %></a></li>
              <li class="dropdown-divider" role="separator"></li>
              <li><a class="dropdown-item btn-wide-mode" data-close-dialog href="#"><%= t(".Fullscreen") %></a></li>

              <% if can? :update, @note %>
                <li class="dropdown-divider" role="separator"></li>
                <li><a class="dropdown-item" data-close-dialog href="<%= versions_user_note_path(@user, @note) %>"><%= t(".Versions") %></a></li>
                <li class="dropdown-divider" role="separator"></li>
                <li><a class="dropdown-item" data-close-dialog href="<%= edit_user_note_path(@user, @note) %>"><%= t(".Edit") %></a></li>
              <% end %>

              <% if can? :destroy, @note %>
                <li class="dropdown-divider" role="separator"></li>
                <li class="text-danger"><a class="dropdown-item" data-close-dialog data-method="delete" href="<%= user_note_path(@user, @note) %>" data-confirm="<%= t(".Are you sure delete?") %>"><%= t(".Delete") %></a></li>
              <% end %>
            </ul>
          </details>
        </div>
        <% end %>
      </div>

      <div class="doc-info">
        <%= t(".Last edit by") %> <%= user_name_tag(@note.user) %> <%= t(".edited at") %> <%= timeago @note.body_updated_at %>
      </div>

      <div class="markdown-body markdown-with-toc" data-turbolinks="false">
        <%= raw @note.body_html %>
      </div>

      <div class="doc-reaction note-reaction">
        <%= react_component "reactions/Index", {
          subjectType: "Note",
          subjectId: @note.id,
          reactions: @note.reactions_as_json,
        } %>
      </div>

      <%= render "readers", note: @note, readers: @readers %>

      <% if @between_notes %>
      <div class="between-docs my-4 clearfix">
        <% if @between_notes[:prev] %>
          <%= link_to @between_notes[:prev].title, @between_notes[:prev].to_path, class: "btn-link btn-prev" %>
        <% end %>

        <% if @between_notes[:next] %>
          <%= link_to @between_notes[:next].title, @between_notes[:next].to_path, class: "btn-link btn-next" %>
        <% end %>
      </div>
      <% end %>

      <div class="doc-comments mt-3 clearfix" id="comment">
        <%= react_component "comments/Index", {
          currentUser: current_user&.as_json(only: %i[id slug name avatar_url]),
          commentableType: "Note",
          commentableId: @note.id,
          watchStatus: @note.watch_comment_status_by_user_id(current_user&.id),
          abilities: {
            update: can?(:update, @issue),
            destroy: can?(:destroy, @issue),
          },
        } %>
      </div>
    </div>
  </div>
  <div class="doc-body-toc" data-turbolinks="false"></div>
  </div>
</div>
<%= react_component("QuickScroll") %>

app/views/notes/versions.html.erb
<% content_for :subnav do %>
<div class="reader-navbar versions-navbar">
  <div class="container">
    <div class="navbar-title">
      <span class="hide-sm">
        <a href="<%= @note.to_path %>" title="<%= @note.title %>"><%= truncate @note.title, length: 25 %></a>
        <span class= "divider">/</span>
        <span class="doc-title"><%= t(".Versions") %></span>
      </span>
    </div>
    <div class="navbar-buttons d-flex flex-items-center">
      <%= form_with(model: @note, url: revert_user_note_path(@user, @note),
        local: true, remote: true) do |form| %>
        <input type="hidden" name="version_id">
        <button type="submit" disabled class="btn btn-sm btn-revert text-primary hover-primary"><%= t(".Revert") %></button>
        <%= link_to t(".Cancel"), @note.to_path, class: "btn btn-sm" %>
      <% end %>
      <span class="diff-toggle">
        <label for="version-diff-toggle">
          <input type="checkbox" id="version-diff-toggle">
          <%= t(".Diff mode") %>
        </label>
      </span>
    </div>
  </div>
</div>
<% end %>

<div class="doc-page flex-wrap">
  <div class="doc-sidebar version-sidebar py-4 flex-justify-start overflow-auto border-right">
    <%= render partial: "versions/version", locals: { version: @current_version, current: true } %>
    <div class="version-items" data-selected-id="<%= @current_version.id %>">
      <%= render "versions" %>
    </div>
  </div>
  <div id="previus-version-content" style="display: none">
    <%= raw(@previous_version&.body_html || "") %>
  </div>
  <div class="doc-main main-content py-4">
    <h1 class="doc-title"><%= @note.title %></h1>
    <div class="version-preview">
      <div class="markdown-body">
        <%= raw @current_version.body_html %>
      </div>
    </div>
    <div class="version-diff" style="display: none"><div class="markdown-body"></div></div>
  </div>
</div>

app/views/notes/versions.js.erb
var selectedVersionId = $(".version-sidebar .version-items").data("selected-id");
$(".version-sidebar .version-items").html('<%= escape_javascript(render("versions")) %>');
$(".version-item-" + selectedVersionId).addClass("selected");
document.dispatchEvent(new Event("turbolinks:load"));