config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphql/explorer", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  get "/health", to: proc { [200, {}, ["ok"]] }

  devise_for :users, path: "account", controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords"
  }
  get "/account/sign_in/ldap" => "users/ldaps#new", :as => :new_ldap_user_session

  # /admin
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web, at: "/admin/sidekiq"
    mount ExceptionTrack::Engine, at: "/admin/exception-track"
    mount PgHero::Engine, at: "/admin/pghero"
  end

  namespace :admin do
    root to: "dashboards#show"
    resource :dashboard do
      collection do
        post :reindex
      end
    end
    resource :settings do
      collection do
        post :test_mail
      end
    end
    resources :integrations
    resources :groups do
      member do
        post :restore
      end
    end
    resources :users do
      member do
        post :restore
      end
    end
    resources :repositories do
      member do
        post :restore
      end
    end
    resources :docs do
      member do
        post :restore
      end
    end
    resources :comments
    resources :shares
    resources :issues
    resources :notes do
      member do
        post :restore
      end
    end
  end

  # short attachment url
  get "/uploads/:id" => "blobs#show", :as => :upload

  resources :notifications do
    collection do
      get :all
      post :read
      delete :clean
    end
  end

  resource :account_settings, as: :account_settings, path: "account/settings" do
    collection do
      get :account
    end
  end

  root to: "dashboards#index"
  resource :dashboard do
    member do
      get :activities
      get :docs
      get :repositories
      get :groups
      get :stars
      get :explore
    end
  end
  # GET /new
  get "new", to: "repositories#new", as: :new_repository
  # GET /new/import
  get "new/import", to: "repositories#import", as: :import_repository
  resource :autocomplete do
    collection do
      get :users
    end
  end

  # GET /groups/new, POST /groups
  resources :groups, only: %i[new create] do
    member do
      get :search
    end
    resources :group_members, as: :members, path: :members
    resource :group_settings, as: :settings, path: :settings
  end
  # GET /notes/new, POST /notes
  resources :notes, only: %i[new create]
  resources :versions
  resource :search do
    collection do
      get :docs
      get :repositories
      get :groups
      get :users
      get :notes
      get :issues
    end
  end
  resources :comments do
    member do
      get :reply
      get :in_reply
    end
    collection do
      post :watch
      delete :watch
    end
  end
  resources :shares

  # NOTE! Keep :profile routes bottom of routes.rb
  resources :repositories, only: %i[index create]
  resources :users, id: /[#{BlueDoc::Slug::FORMAT}]*/o, path: "", as: "users" do
    member do
      post :follow
      delete :unfollow
    end
    resources :notes, only: %i[index create edit show update destroy] do
      member do
        get :raw
        get :versions
        patch :revert
        post :action
        delete :action
        # PRO-begin
        get :readers
        # PRO-end
        post :pdf
      end
    end
    resources :repositories, path: "", as: "repositories", only: %i[show update destroy] do
      resource :services do
        collection do
          get :jira_issues
        end
      end
      member do
        get :docs, path: "docs/list"
        get :search, path: "docs/search"
        post :action
        delete :action
      end
      resource :repository_settings, path: "settings", as: :settings do
        collection do
          get :show, path: "profile"
          put :update, path: "profile"
          patch :update, path: "profile"
          delete :destroy, path: "profile"
          get :advanced
          patch :transfer
          get :docs
          post :docs
          post :export
          get :export
          get :collaborators
          post :collaborators
          post :collaborator
          delete :collaborator
          post :retry_import
          get :integrations
          post :jira
        end
      end
      resources :docs, only: %i[new create]
      resources :labels, path: "issues/labels"
      resources :issues do
        collection do
          get :closed
        end
        member do
          post :assignees
          post :labels
        end
      end
      resources :docs, path: "", only: %i[show edit update destroy] do
        member do
          get :raw
          post :pdf
          get :lock
          post :lock
          post :action
          delete :action
          get :versions
          patch :revert
          patch :abort_draft
          post :share
          # PRO-begin
          get :readers
          # PRO-end
        end
      end
    end
  end
end

app/models/activities/repository.rb
# frozen_string_literal: true

module Activities
  class Repository < Base
    attr_accessor :repository

    def initialize(repository)
      @repository = repository
      super()
    end

    def star
      return if repository.private?

      # actor followers
      user_ids = actor.follower_ids

      Activity.track_activity(:star_repo, repository, user_id: user_ids, actor_id: actor_id)
    end

    def create
      return if repository.private?

      # actor followers
      user_ids = actor.follower_ids

      Activity.track_activity(:create_repo, repository, user_id: user_ids, actor_id: actor_id)
    end

    def transfer
      # watchers
      user_ids = repository.watch_by_user_ids

      Activity.track_activity(:transfer_repo, repository, user_id: user_ids, actor_id: actor_id)
    end
  end
end

app/models/repository.rb
# frozen_string_literal: true

class Repository < ApplicationRecord
  include SoftDelete
  include Slugable
  include Memberable
  include Activityable
  include Exportable

  second_level_cache expires_in: 1.week

  depends_on :soft_delete, :source, :preferences, :toc, :editors, :user_actives, :watches, :privacy, :search, :issues, :jira, :auto_correct

  attr_accessor :last_editor_id

  belongs_to :user
  belongs_to :creator, class_name: "User", required: false
  has_many :docs, dependent: :destroy
  has_many :shares, dependent: :destroy

  validates :name, presence: true, length: {in: 2..50}
  validates :slug, uniqueness: {scope: :user_id, case_sensitive: false}

  scope :recent_updated, -> { order("updated_at desc") }
  scope :with_query, ->(q) { where("name ilike ? or slug ilike ?", "%#{q}%", "%#{q}%") }

  before_validation :check_slug_keywords
  def check_slug_keywords
    if !BlueDoc::Slug.valid_repo?(slug)
      errors.add(:slug, t(".invalid, slug is a keyword", slug: slug))
    end
  end

  def to_path(suffix = nil)
    "/#{user.slug}/#{slug}#{suffix}"
  end

  def transfer(to_slug)
    user = User.find_by_slug(to_slug)
    if user.blank?
      errors.add(:user_id, "Transfer target: [#{to_slug}] does not exists, please check it.")
      return false
    end

    update(user_id: user.id)
    Activities::Repository.new(self).transfer
    true
  end
end

app/models/repository/auto_correct_dependency.rb
# frozen_string_literal: true

class Repository
  before_validation :auto_correct_attributes

  private

  def auto_correct_attributes
    self.name = AutoCorrect.format(name) if name_changed?
    self.description = AutoCorrect.format(description) if description_changed?
  end
end

app/models/repository/editors_dependency.rb
# frozen_string_literal: true

class Repository
  include Editorable
end

app/models/repository/issues_dependency.rb
# frozen_string_literal: true

class Repository
  has_many :issues, dependent: :destroy
  has_many :issue_labels, as: :target, dependent: :destroy, class_name: "Label"

  def has_issues?
    return false if preferences[:has_issues].nil?
    ActiveModel::Type::Boolean.new.cast(preferences[:has_issues])
  end

  DEFAULT_ISSUE_LABELS = {
    discussion: "#3070ff",
    question: "#d62800",
    support: "#00a505",
    invalid: "#6f42c1",
    duplicate: "#008080",
    wontfix: "#5a5a5a"
  }

  def ensure_default_issue_labels
    return false if issue_labels.any?
    create_default_issue_labels!
  end

  def create_default_issue_labels!
    Label.transaction do
      DEFAULT_ISSUE_LABELS.each_key do |name|
        Label.create!(target: self, title: name.to_s.titleize, color: DEFAULT_ISSUE_LABELS[name])
      end
    end
  end

  # Users that for issue assignee
  def issue_assignees
    user_ids = members.pluck(:user_id)
    if user.group?
      user_ids += user.members.pluck(:user_id)
    else
      user_ids << user_id
    end
    users = User.where(id: user_ids.uniq).with_attached_avatar
    users.sort_by { |user| user_ids.index(user.id) }
  end
end

app/models/repository/jira_dependency.rb
# frozen_string_literal: true

class Repository
  has_one :jira_service, dependent: :destroy

  def actived_jira_service
    return JiraService.actived_template if jira_service.nil?
    return unless jira_service.active?
    jira_service
  end
end

app/models/repository/preferences_dependency.rb
# frozen_string_literal: true

class Repository
  serialize :preferences, Hash

  store_accessor :preferences, :has_toc, :has_issues
end

app/models/repository/privacy_dependency.rb
# frozen_string_literal: true

class Repository
  enum privacy: %i[private public], _prefix: :is

  scope :publics, -> { where(privacy: :public) }

  before_update :check_on_make_private

  def private?
    is_private?
  end

  def public?
    is_public?
  end

  private

  def check_on_make_private
    if privacy_changed? && private?
      destroy_depend_activities
    end
  end
end

app/models/repository/search_dependency.rb
# frozen_string_literal: true

class Repository
  include Searchable

  def as_indexed_json(_options = {})
    {
      slug: slug,
      title: name,
      body: description,
      search_body: _search_body,
      repository_id: id,
      user_id: user_id,
      repository: {
        public: public?
      },
      deleted: deleted?
    }
  end

  def indexed_changed?
    saved_change_to_deleted_at? ||
      saved_change_to_privacy? ||
      saved_change_to_name? ||
      saved_change_to_description?
  end

  def _search_body
    [user&.fullname, description].join("\n\n")
  end
end

app/models/repository/soft_delete_dependency.rb
# frozen_string_literal: true

class Repository
  include SoftDelete

  # PRO-begin
  set_callback :restore, :before do
    restore_dependents(:docs)
  end
  # PRO-end
end

app/models/repository/toc_dependency.rb
# frozen_string_literal: true

class Repository
  has_many :tocs

  def has_toc?
    return true if preferences[:has_toc].nil?
    ActiveModel::Type::Boolean.new.cast(preferences[:has_toc])
  end

  def toc_html(prefix: nil)
    BlueDoc::Toc.parse(toc_text).to_html(prefix: prefix)
  end

  def toc_text
    tocs.to_text
  end

  def toc_json
    BlueDoc::Toc.parse(toc_text).to_json
  end

  # sort docs as Toc order
  def toc_ordered_docs
    @toc_ordered_docs ||= tocs.nested_tree.includes(:doc).collect(&:doc).compact
  end
end

app/models/repository/user_active_dependency.rb
# frozen_string_literal: true

class Repository
  has_many :user_actives, as: :subject, dependent: :destroy
  after_commit :track_user_active, on: :create

  private
    def track_user_active
      return false if Current.user.blank?
      UserActive.track(self, user_id: Current.user.id)
      UserActive.track(self.user, user_id: Current.user.id)
    end
end

app/models/repository/user_actives_dependency.rb
# frozen_string_literal: true

class Repository
  has_many :user_actives, as: :subject, dependent: :destroy
  after_commit :track_user_active, on: :create

  private

  def track_user_active
    return false if Current.user.blank?
    UserActive.track(self, user_id: Current.user.id)
    UserActive.track(user, user_id: Current.user.id)
  end
end

app/controllers/admin/repositories_controller.rb
# frozen_string_literal: true

class Admin::RepositoriesController < Admin::ApplicationController
  before_action :set_repository, only: [:show, :edit, :update, :destroy, :restore]

  def index
    @repositories = Repository.unscoped.includes(:user).order("id desc")
    if params[:q]
      q = "%#{params[:q]}%"
      @repositories = @repositories.where("name ilike ? or slug ilike ? or description ilike ?", q, q, q)
    end
    if params[:user_id]
      @repositories = @repositories.where(user_id: params[:user_id])
    end
    @repositories = @repositories.page(params[:page])
  end

  def show
  end

  def new
    @repository = Repository.new
  end

  def edit
  end

  def create
    @repository = Repository.new(repository_params)

    if @repository.save
      redirect_to admin_repositories_path, notice: t(".Repository was successfully created")
    else
      render :new
    end
  end

  def update
    if @repository.update(repository_params)
      redirect_to admin_repositories_path, notice: t(".Repository was successfully updated")
    else
      render :edit
    end
  end

  def destroy
    @repository.destroy
    redirect_to admin_repositories_path(user_id: @repository.user_id, q: @repository.slug), notice: t(".Repository was successfully deleted")
  end

  def restore
    @repository.restore
    redirect_to admin_repositories_path(user_id: @repository.user_id, q: @repository.slug), notice: t(".Repository was successfully restored")
  end

  private

  def set_repository
    @repository = Repository.unscoped.find(params[:id])
  end

  def repository_params
    params.require(:repository).permit!
  end
end

app/controllers/repositories_controller.rb
# frozen_string_literal: true

class RepositoriesController < Users::ApplicationController
  before_action :authenticate_anonymous!
  before_action :authenticate_user!, only: %i[new import edit create update destroy action]

  before_action :set_user, only: %i[show edit update destroy docs search action]
  before_action :set_repository, only: %i[show edit update destroy docs search action]

  def index
    authorize! :read, @user
  end

  # /new
  def new
    @repository = Repository.new(user_id: params[:user_id] || current_user.id)
  end

  # /new/import
  def import
    @repository = Repository.new(user_id: params[:user_id] || current_user.id)
    params[:_by] = "import"
    render :new
  end

  # POST /repositories
  def create
    repository_params[:slug].strip!
    @repository = Repository.new(repository_params)

    authorize! :create, @repository

    respond_to do |format|
      if @repository.save
        @repository.import_from_source
        Activities::Repository.new(@repository).create

        notice = t(".Repository was successfully created")
        if @repository.source?
          notice = t(".Repository was successfully created, and executed importing in background")
        end

        format.html { redirect_to @repository.to_path, notice: notice }
        format.json { render :show, status: :created, location: @repository }
      else
        format.html { render :new }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /:user/:repo
  def show
    authorize! :read, @repository

    if @repository.has_toc?
      @tocs = graphql_query(:repositoryTocs, "repositoryId: #{@repository.id}", "id, docId, title, url, parentId, depth")
    else
      docs
      render "docs"
    end
  end

  # GET /:user/:repo/docs/list
  def docs
    authorize! :read, @repository
  end

  # GET /:user/:repo/docs/search
  def search
    if params[:q].blank?
      return redirect_to docs_user_repository_path(@user, @repository)
    end

    authorize! :read, @repository

    @result = BlueDoc::Search.new(:docs, params[:q], repository_id: @repository.id, include_private: true).execute.page(params[:page])
  end

  def action
    authorize! :read, @repository

    if request.post?
      User.create_action(params[:action_type], target: @repository, user: current_user)

      if params[:action_type] == "star"
        Activities::Repository.new(@repository).star
      end
    else
      User.destroy_action(params[:action_type], target: @repository, user: current_user)
    end
    @repository.reload
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_repository
    @repository = @user.owned_repositories.find_by_slug!(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def repository_params
    params.require(:repository).permit(:user_id, :slug, :name, :description, :privacy, :gitbook_url, :import_archive)
  end
end

app/helpers/admin/repositories_helper.rb
# frozen_string_literal: true

module Admin::RepositoriesHelper
end

app/helpers/repositories_helper.rb
# frozen_string_literal: true

module RepositoriesHelper
  def repository_name_tag(repo, opts = {})
    return "" if repo.blank?
    return "" if repo.user.blank?

    if opts[:with_icon]
      link_to icon_tag("repo", label: repo.name), repo.to_path, class: "repository-name icon-middle-wrap"
    else
      link_to repo.name, repo.to_path, class: "repository-name"
    end
  end

  def repository_path_tag(repo)
    return "" if repo.blank?
    return "" if repo.user.blank?

    divider = %( <span class="divider">/</span> )

    text = safe_join([repo.user.name, repo.name], raw(divider))

    link_to(text, repo.to_path, class: "repository-path")
  end
end

app/views/repositories/_card.html.erb
<div class="repository-card">
  <div class="mb-1 text-main">
    <% if defined?(current_group) && current_group.id != repository.user_id %>
    <%= user_name_tag(repository.user) %> /
    <% end %>
    <%= repository_name_tag(repository) %>
  </div>
  <div class="desc text-gray">
    <%= repository.description %>
  </div>
  <div class="f6 mt-2">
    <span class="counter text-gray mr-2 icon-middle-wrap"><%= icon_tag("star") %> <%= repository.stars_count %></span>
    <span class="updated text-gray-light"><%= t("updated at") %> <%= timeago repository.updated_at %></span>
  </div>
</div>

app/views/repositories/_doc.html.erb
<% if doc %>
  <div class="doc-item list-item list-avatar" id="doc-<%= doc.id %>">
    <div class="avatar-box icon-box icon-doc">
      <%= icon_tag("avatar-doc") %>
    </div>
    <div class="title text-overflow icon-middle-wrap d-flex">
      <%= doc_title_tag(doc) %>
      <% if doc.share %>
        <i class="fas fa-share ml-2"></i>
      <% end %>
    </div>
    <span class="time-box"><%= timeago doc.body_updated_at %></span>
    <div class="path">
      <% if @repository && doc.repository_id != @repository.id %>
      <%= user_name_icon_tag(doc.repository&.user, with_icon: true) %> /
      <%= repository_name_tag(doc.repository, with_icon: true) %>
      <% end %>
      <%= user_name_tag(doc.last_editor) %>
    </div>
    <div class="action action-icon text-gray">
      <%= link_to icon_tag("edit"), doc.to_path("/edit") %>
      <% if can? :destroy, doc %>
        <%= link_to icon_tag("delete"), doc.to_path, data: { method: :delete, remote: true, confirm: t(".Are you sure delete this Doc?") }, class: "btn-link btn-remove-doc" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/repositories/_empty_docs.html.erb
<div class="blankslate no-data no-doc text-center" data-turbolinks="false">
  <h3><%= t(".There is no documents") %></h3>
  <% if can? :create_doc, @repository %>
  <p><%= t(".You can create first document") %></p>
  <p><%= link_to t(".Create doc"), @repository.to_path("/docs/new"), class: "btn btn-primary" %></p>
  <% end %>
</div>

app/views/repositories/_import_status.html.erb
<% if @repository.source? && can?(:update, @repository)  %>
  <% if @repository.source.running? %>
  <div class="repo-import-status">
    <div class="repo-import-running">
      <%= flash_block_tag(:notice, t(".Repository import still running, please wait")) %>
    </div>
  </div>
  <% elsif @repository.source.failed? %>
  <div class="repo-import-status">
    <div class="repo-import-failed border p-3">
      <p><%= t(".Repository import was failed") %></p>
      <div class="form-group">
        <textarea class="form-control mt-2" readonly rows="8"><%= @repository.source.message %></textarea>
      </div>
      <%= link_to t(".Retry import"), @repository.to_path("/settings/retry_import"), class: "btn-retry btn btn-primary btn-sm", data: { method: :post } %>
      <%= link_to t(".Abort"), @repository.to_path("/settings/retry_import?abort=1"), class: "btn-abort btn btn-sm", data: { method: :post } %>
    </div>
  </div>
  <% end %>
<% end %>

app/views/repositories/_menu.html.erb
<% content_for :subnav do %>
<div class="repo-heading">
  <div class="container">
    <div class="heading clearfix">
      <h1 class="text-gray-light">
        <div class="repo-name">
          <%= group_name_tag @user %> <span class="divider">/</span> <%= repository_name_tag @repository %>
          <% if @repository.private? %>
           <span class="label label-private icon-middle-wrap ml-2"><%= icon_tag("lock") %><%= t(".Private") %></span>
          <% end %>
        </div>
      </h1>

      <div class="heading-actions">
        <div class="repo-actions">
          <%= action_button_tag(@repository, :watch, with_count: true) %>
          <%= action_button_tag(@repository, :star, with_count: true) %>
        </div>
        <nav class="reponav clearfix">
          <%= render_list_items(type: :link, class: "reponav-item", active_class: "selected") do |item|
            if @repository.has_toc?
              item << link_to(t(".Summary"), @repository.to_path, class: "reponav-item")
              item << link_to(t(".Docs"), docs_user_repository_path(@user, @repository), class: "reponav-item reponav-item-docs")
            else
              item << link_to(t(".Docs"), @repository.to_path, class: "reponav-item")
            end
            item << link_to(t(".Search"), search_user_repository_path(@user, @repository), class: "reponav-item reponav-item-docs") if action_name == "search"
            item << link_to(t(".Issues"), @repository.to_path("/issues"), class: "reponav-item reponav-issues", "data-controller" => [:issues, :labels]) if @repository.has_issues?
            item << link_to(t(".Settings"), user_repository_settings_path(@user, @repository), class: "reponav-item", "data-controller" => :repository_settings) if can? :update, @repository
          end %>
        </nav>
      </div>
    </div>
  </div>

</div>
<% end %>

<% content_for :nav_search do %>
<%= render partial: "/layouts/search_nav", locals: { props: { action: @repository.to_path("/docs/search"), scope: t(".Repository"), value: params[:q] } } %>
<% end %>

app/views/repositories/_repository.html.erb
<li class="list-item list-avatar repository-item">
  <div class="avatar-box icon-box icon-repo">
    <%= icon_tag("avatar-repo") %>
  </div>
  <% if local_assigns[:no_path] %>
    <div class="title text-overflow">
      <%= repository_name_tag(repository) %>
      <% if repository.private? %>
        <span class="label label-private icon-middle-wrap ml-2"><%= icon_tag("lock") %><%= t(".Private") %></span>
      <% end %>
    </div>
  <% else %>
    <div class="title text-overflow path">
      <%= user_name_tag(repository.user, with_icon: true) %> /
      <%= repository_name_tag(repository, with_icon: true) %>
      <% if repository.private? %>
        <span class="label label-private icon-middle-wrap ml-2"><%= icon_tag("lock") %><%= t(".Private") %></span>
      <% end %>
    </div>
  <% end %>
  <% if repository.description.present? %>
  <div class="description text-overflow">
    <%= truncate repository.description, length: 150 %>
  </div>
  <% end %>
  <div class="info">
    <span class="stars">
      <%= icon_tag("star-fill") %> <span><%= repository.stars_count %></span>
    </span>
    <span class="watches">
      <%= icon_tag("watches") %> <span><%= repository.watches_count %></span>
    </span>
  </div>
  <div class="time-box">
    <%= timeago repository.updated_at %>
  </div>
</li>

app/views/repositories/action.js.erb
if ($(".data-action-button-reload").length > 0) {
  Turbolinks.visit(window.location);
} else {
  var btnAction = $(".repository-<%= @repository.id %>-<%= params[:action_type ] %>-button");
  var btn = $(".btn", btnAction);
  console.log(btn);
  <% if request.post? %>
    btn.attr("data-method", "delete");
    $("span", btnAction).text(btn.attr("data-undo-label"));
  <% else %>
    btn.attr("data-method", "post");
    $("span", btnAction).text(btn.attr("data-label"));
  <% end %>

  $(".social-count", btnAction).text("<%= @repository.send("#{params[:action_type].pluralize}_count") %>")
}

app/views/repositories/docs.html.erb
<% title_tag t(".Docs"), @repository.name %>

<%= render "menu" %>

<%= react_component "repositories/DocList", {
  repositoryId: @repository.id,
  newDocURL: @repository.to_path("/docs/new"),
  abilities: {
    update: can?(:update, Doc.new(repository_id: @repository.id)),
    destroy: can?(:destroy, Doc.new(repository_id: @repository.id)),
  },
} %>

app/views/repositories/new.html.erb
<% title_tag t(".New Repository") %>

<div class="main-content">
  <div class="container">
    <%
      groups = current_user.groups.with_attached_avatar.to_a
      groups.unshift(current_user)
    %>

    <%= react_component "repositories/NewRepository", {
      type: params[:_by],
      provider: params[:provider],
      action: repositories_path,
      repository: @repository.as_rc_json(only: %i[slug name user_id descrption gitbook_url privacy]),
      groups: groups.as_json(only: %i[id slug name], methods: :avatar_url),
    } %>
  </div>
</div>

app/views/repositories/search.html.erb
<% title_tag t(".Search Docs"), @repository.name %>

<%= render "menu" %>

<div class="repository-docs">
  <div class="search-results">
    <% if @result.records.blank? %>
    <div class="blankslate">
      <%= t(".Can not find any Doc like") %> "<span class="text-red"><%= params[:q] %></span>" <%= t(".in this Repository") %>
    </div>
    <% end %>

    <% @result.records.each_with_hit do |item, hit| %>
      <%= render "/searches/doc", item: item, hit: hit %>
    <% end %>
    <%= paginate @result %>
  </div>
</div>

app/views/repositories/show.html.erb
<% title_tag @repository.name %>
<%= render "menu" %>
<%
toc_html = @repository.toc_html(prefix: @repository.to_path("/"))
%>
<%= render "import_status" %>
<div class="repo-desc text-center">
  <div class="text-gray mb-2"><%= @repository.description %></div>
  <% if @repository.source? && @repository.source.provider == "gitbook" %>
    <div class="source text-gray">
      <%= icon_tag("code-fork") %> <span class="source-url"><%= @repository.source_url %></span>
    </div>
  <% end %>
</div>
<div class="repo-toc">
  <% if @repository.toc_json.blank? || @repository.toc_json == "[]" %>
    <%= render "empty_docs" %>
  <% else %>
    <div class="toc-list">
      <%= react_component("toc-tree/index", {
      type: 'center',
      repository: {
        path: @repository.to_path,
        name: @repository.name,
        has_toc: @repository.has_toc?,
        id: @repository.id
      },
      user: {
        path: @user.to_path,
        name: @user.name
      },
      tocs: @tocs,
      abilities: {
        update: can?(:create_doc, @repository),
      }
    } ) %>
    </div>
  <% end %>
</div>