config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphql/explorer", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  get "/health", to: proc { [200, {}, ["ok"]] }

  devise_for :users, path: "account", controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords"
  }
  get "/account/sign_in/ldap" => "users/ldaps#new", :as => :new_ldap_user_session

  # /admin
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web, at: "/admin/sidekiq"
    mount ExceptionTrack::Engine, at: "/admin/exception-track"
    mount PgHero::Engine, at: "/admin/pghero"
  end

  namespace :admin do
    root to: "dashboards#show"
    resource :dashboard do
      collection do
        post :reindex
      end
    end
    resource :settings do
      collection do
        post :test_mail
      end
    end
    resources :integrations
    resources :groups do
      member do
        post :restore
      end
    end
    resources :users do
      member do
        post :restore
      end
    end
    resources :repositories do
      member do
        post :restore
      end
    end
    resources :docs do
      member do
        post :restore
      end
    end
    resources :comments
    resources :shares
    resources :issues
    resources :notes do
      member do
        post :restore
      end
    end
  end

  # short attachment url
  get "/uploads/:id" => "blobs#show", :as => :upload

  resources :notifications do
    collection do
      get :all
      post :read
      delete :clean
    end
  end

  resource :account_settings, as: :account_settings, path: "account/settings" do
    collection do
      get :account
    end
  end

  root to: "dashboards#index"
  resource :dashboard do
    member do
      get :activities
      get :docs
      get :repositories
      get :groups
      get :stars
      get :explore
    end
  end
  # GET /new
  get "new", to: "repositories#new", as: :new_repository
  # GET /new/import
  get "new/import", to: "repositories#import", as: :import_repository
  resource :autocomplete do
    collection do
      get :users
    end
  end

  # GET /groups/new, POST /groups
  resources :groups, only: %i[new create] do
    member do
      get :search
    end
    resources :group_members, as: :members, path: :members
    resource :group_settings, as: :settings, path: :settings
  end
  # GET /notes/new, POST /notes
  resources :notes, only: %i[new create]
  resources :versions
  resource :search do
    collection do
      get :docs
      get :repositories
      get :groups
      get :users
      get :notes
      get :issues
    end
  end
  resources :comments do
    member do
      get :reply
      get :in_reply
    end
    collection do
      post :watch
      delete :watch
    end
  end
  resources :shares

  # NOTE! Keep :profile routes bottom of routes.rb
  resources :repositories, only: %i[index create]
  resources :users, id: /[#{BlueDoc::Slug::FORMAT}]*/o, path: "", as: "users" do
    member do
      post :follow
      delete :unfollow
    end
    resources :notes, only: %i[index create edit show update destroy] do
      member do
        get :raw
        get :versions
        patch :revert
        post :action
        delete :action
        # PRO-begin
        get :readers
        # PRO-end
        post :pdf
      end
    end
    resources :repositories, path: "", as: "repositories", only: %i[show update destroy] do
      resource :services do
        collection do
          get :jira_issues
        end
      end
      member do
        get :docs, path: "docs/list"
        get :search, path: "docs/search"
        post :action
        delete :action
      end
      resource :repository_settings, path: "settings", as: :settings do
        collection do
          get :show, path: "profile"
          put :update, path: "profile"
          patch :update, path: "profile"
          delete :destroy, path: "profile"
          get :advanced
          patch :transfer
          get :docs
          post :docs
          post :export
          get :export
          get :collaborators
          post :collaborators
          post :collaborator
          delete :collaborator
          post :retry_import
          get :integrations
          post :jira
        end
      end
      resources :docs, only: %i[new create]
      resources :labels, path: "issues/labels"
      resources :issues do
        collection do
          get :closed
        end
        member do
          post :assignees
          post :labels
        end
      end
      resources :docs, path: "", only: %i[show edit update destroy] do
        member do
          get :raw
          post :pdf
          get :lock
          post :lock
          post :action
          delete :action
          get :versions
          patch :revert
          patch :abort_draft
          post :share
          # PRO-begin
          get :readers
          # PRO-end
        end
      end
    end
  end
end

app/models/notification.rb
# frozen_string_literal: true

# Auto generate with notifications gem.
class Notification < ActiveRecord::Base
  include NotifyTrackable
  include Notifications::Model

  delegate :email, to: :user
  delegate :name, to: :actor, prefix: true, allow_nil: true

  serialize :meta, Hash

  NOTIFY_TYPES = %w[add_member repo_import comment mention issue_assign new_issue close_issue reopen_issue]

  before_create :bind_relation_for_target
  after_commit :create_email_notify, on: [:create]

  def self.allow_type?(notify_type)
    NOTIFY_TYPES.include?(notify_type)
  end

  def self.track_notification(notify_type, target, user: nil, user_id: nil, actor_id: nil, meta: nil)
    notify_type = notify_type.to_s
    return false unless allow_type?(notify_type)

    actor_id ||= Current.user&.id
    return false if actor_id.blank?
    return false if target.blank?

    user_ids = get_user_ids(user: user, user_id: user_id)
    user_ids.delete actor_id

    return false if user_ids.blank?

    notification_params = {
      notify_type: notify_type,
      target: target,
      target_type: target.class.name,
      target_id: target.id,
      actor_id: actor_id,
      meta: meta&.deep_symbolize_keys
    }

    fill_depend_id_for_target(notification_params)

    # create Activity for receivers, for dashboard timeline
    Notification.transaction do
      user_ids.each do |uid|
        note = Notification.new(notification_params)
        note.user_id = uid

        # ingore create, if user not has ability to read target
        ability = Ability.new(User.new(id: uid))
        next if ability.cannot?(:read, note.target)

        note.save!
      end
    end
  end

  # mark target_type, target_ids as read
  def self.read_targets(user, target_type:, target_id:)
    return if user.blank?
    Notification.where(user: user, target_type: target_type, target_id: target_id).update_all(read_at: Time.now)
  end

  def target_url
    case notify_type
    when "add_member" then target&.subject&.to_url
    when "repo_import", "comment", "mention", "issue_assign", "new_issue", "close_issue", "reopen_issue"
      target&.to_url
    else
      Setting.host
    end
  end

  def target_mention_fragment
    return @target_mention_fragment if defined? @target_mention_fragment
    @target_mention_fragment = case target_type
                               when "Doc" then BlueDoc::HTML.mention_fragments(target&.body_html, user&.slug).join("<br /><br />")
                               when "Comment", "Issue"
                                 target&.body_html
                               else
                                 ""
    end

    @target_mention_fragment
  end

  def mail_body
    ApplicationController.renderer.render "/notifications/body/#{notify_type}", layout: false, locals: {notification: self}
  rescue => e
    BlueDoc::Error.track(e, title: "notification body render failed, fallbacked to title")
    mail_title
  end

  def mail_title
    html = ApplicationController.renderer.render "/notifications/title/#{notify_type}", layout: false, locals: {notification: self}
    html.gsub(/<.+?>/, "").gsub(/\s+/, " ").strip
  end

  # comment-doc-id
  def mail_message_id
    message_ids = [notify_type]

    case notify_type
    when "comment"
      message_ids += [target&.commentable_type, target&.commentable_id]
    when "add_member"
      message_ids += [target&.subject_type, target&.subject_id]
    when "mention"
      message_ids = case target_type
      when "Comment"
        ["comment", target&.commentable_type, target&.commentable_id]
      else
        ["comment", target_type, target_id]
      end
    else
      message_ids += [target_type, target_id]
    end

    message_ids.join("-")
  end

  private

  def bind_relation_for_target
    self.class.fill_depend_id_for_target(self)
  end

  def create_email_notify
    NotificationMailer.with(notification: self).to_user.deliver_later
  end
end

app/controllers/notifications_controller.rb
# frozen_string_literal: true

class NotificationsController < ::ApplicationController
  before_action :authenticate_user!

  def index
    @notifications = notifications.includes(:actor).order("id desc").page(params[:page]).per(10)
    if params[:tab] != "all"
      @notifications = @notifications.where(read_at: nil)
    end
  end

  def show
    @notification = notifications.find_by_id(params[:id])
    # Redirect to /notifications when visit /notifications/:id not found
    # Because some times, mail has sent, but notification was deleted by target depends destroy
    if @notification.blank?
      return redirect_to notifications_path
    end

    Notification.read!(current_user, [@notification.id])

    redirect_to @notification.target_url
  end

  def read
    ids = notifications.where(id: params[:ids]).pluck(:id)
    Notification.read!(current_user, ids)
    redirect_to notifications_path, notice: t(".Success marked notifications as read", num: ids.length)
  end

  def clean
    notifications.delete_all
    redirect_to notifications_path
  end

  private

  def notifications
    raise "You need reqiure user login for /notifications page." unless current_user
    Notification.where(user_id: current_user.id)
  end
end

app/views/notifications/_add_member.html.erb
<%
  member = notification.target
%>

<div class="info">
  <%= user_name_tag(notification.actor) %> <%= t(".has added you as a member of") %>
</div>
<span class="time">
  <%= l notification.created_at, format: :short %>
</span>

<div class="detail">
  <% if member.subject_type == "Repository" %>
    <%= render "/repositories/card", repository: member.subject %>
  <% else %>
    <%= render "/users/card", user: member.subject %>
  <% end %>
</div>

app/views/notifications/_close_issue.html.erb
<%
issue = notification.target
%>

<% if issue %>
  <div class="info">
    <%= notification.actor_name %>
    <%= t(".has closed issue") %>
  </div>
  <span class="time">
    <%= l notification.created_at, format: :short %>
  </span>
  <div class="detail">
    <div class="title"><%= link_to issue.issue_title, notification_url(notification) %></div>
    <div class="f6 mt-2 text-gray"><%= repository_path_tag(issue.repository) %></div>
  </div>
<% end %>

app/views/notifications/_comment.html.erb
<%
  comment = notification.target
%>

<% if comment %>
<div class="info">
  <%= user_name_tag(notification.actor) %> <%= t(".was posted a comment on") %>
  <%= link_to comment.commentable_title, notification_url(notification.id) %>
</div>
<span class="time">
  <%= l notification.created_at, format: :short %>
</span>

<div class="detail markdown-body">
  <%= sanitize_html comment.body_html %>
</div>
<% else %>
<%= t("notifications.Notification been deleted") %>
<% end %>

app/views/notifications/_issue_assign.html.erb
<%
issue = notification.target
%>

<% if issue %>
  <div class="info">
    <%= notification.actor_name %>
    <%= t(".has assigned issue to you") %>
  </div>
  <span class="time">
    <%= l notification.created_at, format: :short %>
  </span>
  <div class="detail">
    <div class="title"><%= link_to issue.issue_title, notification_url(notification) %></div>
    <div class="f6 mt-2 text-gray"><%= repository_path_tag(issue.repository) %></div>
  </div>
<% end %>

app/views/notifications/_mention.html.erb
<%
mentionable = notification.target
%>

<% if mentionable %>
  <div class="info">
    <%= notification.actor_name %>
    <%= t(".was mentioned you in") %>
    <% if mentionable.is_a?(Comment) %>
      <%= mentionable.commentable_title %>
    <% elsif mentionable.is_a?(Doc) %>
      <%= mentionable.title %>
    <% end %>
  </div>
  <span class="time">
    <%= l notification.created_at, format: :short %>
  </span>
  <% if notification.target_mention_fragment.present? %>
  <div class="detail markdown-body">
    <%= sanitize_html notification.target_mention_fragment %>
  </div>
  <% end %>
<% end %>

app/views/notifications/_new_issue.html.erb
<%
issue = notification.target
%>

<% if issue %>
  <div class="info">
    <%= notification.actor_name %>
    <%= t(".has opened new issue") %>
  </div>
  <span class="time">
    <%= l notification.created_at, format: :short %>
  </span>
  <div class="detail">
    <div class="title"><%= link_to issue.issue_title, notification_url(notification) %></div>
    <div class="f6 mt-2 text-gray"><%= repository_path_tag(issue.repository) %></div>
  </div>
<% end %>

app/views/notifications/_notification.html.erb
<div id="notification-<%= notification.id %>"
     data-id="<%= notification.id %>"
     class="activity-item notification notification-<%= notification.notify_type %><%= ' unread' unless notification.read? %>">
  <div class="avatar-box">
    <%= user_avatar_tag notification.actor, style: :medium %>
  </div>
  <div class="infos">
    <%= render "/notifications/#{notification.notify_type}", notification: notification rescue t("notifications.Notification been deleted") %>
  </div>
</div>

app/views/notifications/_reopen_issue.html.erb
<%
issue = notification.target
%>

<% if issue %>
  <div class="info">
    <%= notification.actor_name %>
    <%= t(".has reopened issue") %>
  </div>
  <span class="time">
    <%= l notification.created_at, format: :short %>
  </span>
  <div class="detail">
    <div class="title"><%= link_to issue.issue_title, notification_url(notification) %></div>
    <div class="f6 mt-2 text-gray"><%= repository_path_tag(issue.repository) %></div>
  </div>
<% end %>

app/views/notifications/_repo_import.html.erb
<%
  repo = notification.target
%>

<div class="info">
  <%= t(".Repository") %> <%= repository_name_tag(repo) %> <%= t(".has been imported") %> <strong><%= notification.meta[:status] %></strong>
</div>
<span class="time">
  <%= l notification.created_at, format: :short %>
</span>
<% if notification.meta[:status].to_s == "failed" %>
  <div class="detail markdown-body"><pre class="hightlight"><code><%= notification.meta[:message] %></code></pre></div>
<% else %>
  <div class="detail">
    <%= render "/repositories/card", repository: repo %>
  </div>
<% end %>

app/views/notifications/index.html.erb
<div class="flex-wrap">
<div class="aside-wrap">
  <div class="aside-content">
    <details class="aside-content details-reset menu js-menu">
      <summary><%= icon_tag("menu") %></summary>
      <nav>
       <%= render_list_items(class: "menu-item", type: :link, check_parameters: true) do |li|
        li << link_to(main_app.notifications_path, class: "menu-item") do %>
          <span class="mr-3 icon-middle-wrap"><%= icon_tag("bell", label: t(".Unread")) %></span>
          <b class="counter"><%= unread_notifications_count %></b>
        <% end
        li << link_to(icon_tag("notice", label: t(".All")), main_app.notifications_path(tab: "all"), class: "menu-item")
      end %>
      </nav>
    </details>
  </div>
</div>

<div class="main-wrap">
  <div class="main-content">
    <div class="notifications box">
      <% if params[:tab] == "all" %>
          <%= link_to t(".Clear all"), main_app.clean_notifications_path, class: 'float-right f6 mt-2 hover-danger', method: 'delete' %>
        <% else %>
          <%= form_with scope: :notification, class: "float-right mt-2", url: main_app.read_notifications_path, method: :post do |form| %>
            <% @notifications.each do |note| %>
            <input type="hidden" name="ids[]" value="<%= note.id %>">
            <% end %>
            <button type="submit" class="button-reset f6"><%= t(".Mark as read") %></button>
          <% end %>
        <% end %>
      <h2 class="sub-title">
        <span><% if params[:tab] == "all" %><%= t(".All") %><% else %><%= t(".Unread") %><% end %></span>
      </h2>
      <div class="list">
        <% if @notifications.blank? %>
          <div class="blankslate">
            <% if params[:tab] == "all" %>
              <%= t(".You does not have any notifications") %>
            <% else %>
              <%= t(".You does not have any unread notifications") %>
            <% end %>
          </div>
        <% else %>
          <%= render @notifications %>
        <% end %>
      </div>
    </div>
    <%= paginate @notifications, params: { controller: "notifications", action: "index" } %>
  </div>
</div>
</div>

<script>
  $(".notifications").on("click", ".notification", function(e) {
    e.stopPropagation();
    $note = $(e.currentTarget);
    $note.removeClass("unread");
    Turbolinks.visit("/notifications/" + $note.attr('data-id'));
    return false;
  })
</script>