config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphql/explorer", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  get "/health", to: proc { [200, {}, ["ok"]] }

  devise_for :users, path: "account", controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords"
  }
  get "/account/sign_in/ldap" => "users/ldaps#new", :as => :new_ldap_user_session

  # /admin
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web, at: "/admin/sidekiq"
    mount ExceptionTrack::Engine, at: "/admin/exception-track"
    mount PgHero::Engine, at: "/admin/pghero"
  end

  namespace :admin do
    root to: "dashboards#show"
    resource :dashboard do
      collection do
        post :reindex
      end
    end
    resource :settings do
      collection do
        post :test_mail
      end
    end
    resources :integrations
    resources :groups do
      member do
        post :restore
      end
    end
    resources :users do
      member do
        post :restore
      end
    end
    resources :repositories do
      member do
        post :restore
      end
    end
    resources :docs do
      member do
        post :restore
      end
    end
    resources :comments
    resources :shares
    resources :issues
    resources :notes do
      member do
        post :restore
      end
    end
  end

  # short attachment url
  get "/uploads/:id" => "blobs#show", :as => :upload

  resources :notifications do
    collection do
      get :all
      post :read
      delete :clean
    end
  end

  resource :account_settings, as: :account_settings, path: "account/settings" do
    collection do
      get :account
    end
  end

  root to: "dashboards#index"
  resource :dashboard do
    member do
      get :activities
      get :docs
      get :repositories
      get :groups
      get :stars
      get :explore
    end
  end
  # GET /new
  get "new", to: "repositories#new", as: :new_repository
  # GET /new/import
  get "new/import", to: "repositories#import", as: :import_repository
  resource :autocomplete do
    collection do
      get :users
    end
  end

  # GET /groups/new, POST /groups
  resources :groups, only: %i[new create] do
    member do
      get :search
    end
    resources :group_members, as: :members, path: :members
    resource :group_settings, as: :settings, path: :settings
  end
  # GET /notes/new, POST /notes
  resources :notes, only: %i[new create]
  resources :versions
  resource :search do
    collection do
      get :docs
      get :repositories
      get :groups
      get :users
      get :notes
      get :issues
    end
  end
  resources :comments do
    member do
      get :reply
      get :in_reply
    end
    collection do
      post :watch
      delete :watch
    end
  end
  resources :shares

  # NOTE! Keep :profile routes bottom of routes.rb
  resources :repositories, only: %i[index create]
  resources :users, id: /[#{BlueDoc::Slug::FORMAT}]*/o, path: "", as: "users" do
    member do
      post :follow
      delete :unfollow
    end
    resources :notes, only: %i[index create edit show update destroy] do
      member do
        get :raw
        get :versions
        patch :revert
        post :action
        delete :action
        # PRO-begin
        get :readers
        # PRO-end
        post :pdf
      end
    end
    resources :repositories, path: "", as: "repositories", only: %i[show update destroy] do
      resource :services do
        collection do
          get :jira_issues
        end
      end
      member do
        get :docs, path: "docs/list"
        get :search, path: "docs/search"
        post :action
        delete :action
      end
      resource :repository_settings, path: "settings", as: :settings do
        collection do
          get :show, path: "profile"
          put :update, path: "profile"
          patch :update, path: "profile"
          delete :destroy, path: "profile"
          get :advanced
          patch :transfer
          get :docs
          post :docs
          post :export
          get :export
          get :collaborators
          post :collaborators
          post :collaborator
          delete :collaborator
          post :retry_import
          get :integrations
          post :jira
        end
      end
      resources :docs, only: %i[new create]
      resources :labels, path: "issues/labels"
      resources :issues do
        collection do
          get :closed
        end
        member do
          post :assignees
          post :labels
        end
      end
      resources :docs, path: "", only: %i[show edit update destroy] do
        member do
          get :raw
          post :pdf
          get :lock
          post :lock
          post :action
          delete :action
          get :versions
          patch :revert
          patch :abort_draft
          post :share
          # PRO-begin
          get :readers
          # PRO-end
        end
      end
    end
  end
end

app/controllers/admin/dashboards_controller.rb
# frozen_string_literal: true

module Admin
  class DashboardsController < Admin::ApplicationController
    def show
      @statuses = StatusPage.check(request: request)
    end

    def reindex
      SearchReindexJob.perform_later
      redirect_to admin_root_path, notice: t(".Search indexes has running reindex with async")
    end
  end
end

app/controllers/dashboards_controller.rb
# frozen_string_literal: true

class DashboardsController < ApplicationController
  before_action :authenticate_anonymous!
  before_action :authenticate_user!

  def index
    @groups = current_user.groups.with_attached_avatar.limit(100)
    @recent_docs = current_user.user_actives.docs.limit(6)
    @recent_repos = current_user.user_actives.repositories.limit(12)
    @recent_issues = current_user.user_actives.issues.limit(12)

    @watched_repositories = current_user.watch_repositories.order("updated_at desc").includes(:user).page(params[:page]).per(6)
    @doc_groups = {}
    @watched_repositories.each do |repo|
      @doc_groups[repo.id] = repo.docs.order("body_updated_at desc").limit(5)
    end
  end

  def activities
    @activities = current_user.activities.includes(:actor, :target).page(params[:page]).per(20)
  end

  def show
    redirect_to root_path
  end

  def groups
    @groups = current_user.groups.with_attached_avatar.page(params[:page]).per(12)
  end

  def repositories
    @repositories = current_user.user_actives.repositories.includes(:user).page(params[:page]).per(12)
  end

  def docs
    @docs = current_user.user_actives.docs.page(params[:page]).per(6)
  end

  # GET /dashboard/stars?tab=
  def stars
    case params[:tab]
    when "docs"
      @docs = current_user.star_docs.includes(repository: :user).page(params[:page]).per(12)
    when "notes"
      @notes = current_user.star_notes.includes(:user).page(params[:page]).per(12)
    else
      @repositories = current_user.star_repositories.includes(:user).page(params[:page]).per(12)
    end
  end

  def explore
    @groups = Group.order("members_count desc").limit(12)
    @repositories = Repository.publics.order("watches_count desc").limit(12)
  end
end

app/views/admin/dashboards/show.html.erb
<div class="col-12 clearfix">
  <div class="col-12 col-md-5 float-left pr-md-3">
    <div class="box mb-3">
      <div class="box-header">
        <h3 class="box-title"><%= t(".Tools") %></h3>
      </div>
      <div class="box-row">
        <a href="<%= admin_settings_path %>" target="_blank" class="btn mb-2"><%= icon_tag("gear") %> <%= t(".Settings") %></a>
        <a href="/admin/sidekiq" target="_blank" class="btn mb-2"><%= icon_tag("server") %> <%= t(".Background Jobs") %></a>
        <a href="/admin/pghero" target="_blank" class="btn mb-2"><%= icon_tag("dashboard") %> <%= t(".Database Stats") %></a>
      </div>
      <div class="box-row">
        <a href="<%= edit_admin_integration_path(id: :jira) %>" class="btn mb-2"><%= t(".Integrations") %></a>
      </div>
      <div class="box-row">
        <a href="<%= reindex_admin_dashboard_path %>" data-method="post" class="btn mb-2"><%= t(".Rebuild Search Index") %></a>
      </div>
      <div class="box-row">
        <%= form_tag(exception_track.export_logs_path, method: 'post', style: "display: inline") do %>
          <button type="submit" class="btn mb-2"><%= t(".Export Exceptions") %></button>
        <% end %>
        <a href="/admin/exception-track" target="_blank" class="btn mb-2"><%= icon_tag("error") %> <%= t(".Exceptions") %></a>
      </div>
    </div>
  </div>

  <div class="col-12 col-md-7 float-left">
    <div class="box mb-3">
      <div class="box-header">
        <h3 class="box-title"><%= t(".Service statuses") %></h3>
      </div>
      <ul>
        <% @statuses[:results].each do |status| %>
         <li class="box-row clearfix">
           <div><span class="name"><%= t(".Service.#{status[:name]}")  %></span>
           <span class="float-right <%= status[:status].downcase == "error" ? "text-red" : "text-green" %>"><%= status[:status] %></span></div>
           <div class="message text-red">
             <%= status[:message] %>
           </div>
         </li>
         <% end %>
      </ul>
    </div>
  </div>
</div>

<div class="box mb-3">
  <div class="box-header">
    <h3 class="box-title"><%= t(".Statistics") %></h3>
  </div>

  <div class="box-row clearfix">
    <div class="clearfix border-bottom text-center">
      <div class="col-4 float-left p-4">
        <h2 class="text-blue"><%= User.where(type: "User").count %></h2>
        <div class="text-gray-dark"><%= t("admin.User") %></div>
      </div>
      <div class="col-4 float-left p-4">
        <h2 class="text-blue"><%= Group.count %></h2>
        <div class="text-gray-dark"><%= t("admin.Group") %></div>
      </div>
      <div class="col-4 float-left p-4">
        <h2 class="text-blue"><%= Repository.count %></h2>
        <div class="text-gray-dark"><%= t("admin.Repository") %></div>
      </div>
    </div>
    <div class="clearfix text-center">
      <div class="col-3 float-left p-4">
        <h2 class="text-blue"><%= Doc.count %></h2>
        <div class="text-gray-dark"><%= t("admin.Doc") %></div>
      </div>
      <div class="col-3 float-left p-4">
        <h2 class="text-blue"><%= Note.count %></h2>
        <div class="text-gray-dark"><%= t("admin.Note") %></div>
      </div>
      <div class="col-3 float-left p-4">
        <h2 class="text-blue"><%= Issue.count %></h2>
        <div class="text-gray-dark"><%= t("admin.Issue") %></div>
      </div>
      <div class="col-3 float-left p-4">
        <h2 class="text-blue"><%= Comment.count %></h2>
        <div class="text-gray-dark"><%= t("admin.Comment") %></div>
      </div>
    </div>
    <div class="clearfix text-center">
      <div class="col-4 float-left p-4">
        <h2 class="text-blue"><%= Share.count %></h2>
        <div class="text-gray-dark"><%= t("admin.Share") %></div>
      </div>
      <div class="col-4 float-left p-4">
        <h2 class="text-blue"><%= Notification.count %></h2>
        <div class="text-gray-dark"><%= t("admin.Notification") %></div>
      </div>
      <div class="col-4 float-left p-4">
        <h2 class="text-blue"><%= Activity.count %></h2>
        <div class="text-gray-dark"><%= t("admin.Activity") %></div>
      </div>
    </div>
  </div>
</div>